#! /usr/bin/env bash

# Copyright (c) 2018-2021 Ryan Parman <http://ryanparman.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# http://opensource.org/licenses/MIT

# Usage:
#   git open {remote} {branch}

TRACKING="$(git status -sb | head -n 1 | sed -Ee's#(.*)\.\.\.([^/]+)/(.*)$#\2 \3#')"
REMOTE=${1:-$(echo "$TRACKING" | awk '{print $1}')}
BRANCH=${2:-$(echo "$TRACKING" | awk '{print $2}')}

BASEURL="$(git config --get "remote.$REMOTE.url" | sed -Ene's#^(git@|https://)github(.mheducation)?.com(/|:)([^/]*)/(.*).git#https://github\2.com/\4/\5#p')"
GHURL="$BASEURL/tree/$BRANCH"

if hash open 2> /dev/null; then
    open "$GHURL"
else
    echo "$GHURL"
fi
